version: '3' # Docker Composeのバージョンを指定します。
services: # コンテナ化されるサービスを定義します。
  fastapi-introduction: # サービス名です。
    build: . # 現在のディレクトリにあるDockerfileを使用してイメージをビルドします。
    volumes: # ホストとコンテナ間でデータを共有するためのボリュームをマウントします。
      - .dockervenv:/src/.venv # ホストの`.dockervenv`ディレクトリをコンテナの`/src/.venv`にマウントします。
      - .:/src # 現在のディレクトリをコンテナの`/src`にマウントします。
    ports: # ホストとコンテナのポートをマッピングします。
      - 63000:8000 # ホストの63000ポートをコンテナの8000ポートに転送します。